spring.application.name=book-selling

# MySQL datasource
spring.datasource.url=jdbc:mysql://localhost:3306/bookdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Mail settings (thêm giá trị của bạn ở đây)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=huuthinh123v@gmail.com
spring.mail.password=xtsu pmgx kpww qfpg
spring.mail.from=Book Store <apathyisacurse@gmail.com>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

# Spring Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# 1. Mở giới hạn tối đa cho Spring
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

# 2. CHÌA KHÓA: Tránh xung đột với Spring Security
spring.servlet.multipart.resolve-lazily=true

# 3. Mở giới hạn cho Tomcat (người gác cổng)
server.tomcat.max-swallow-size=15MB
server.tomcat.max-http-form-post-size=15MB
# Tăng giới hạn số lượng part trong multipart form
server.tomcat.max-part-count=500